### PR TITLE
xenomai implementation of thread, added sleep.hpp

### PR DESCRIPTION
**Pull request by vincentberenz**
## issue solved

Some code for xenomai had not been yet implemented / tested.
Here the implementation of thread has been updated for xenomai.

Misc: sleep.hpp has been added, that provides a microsleep function working on all OS

## how it was tested

demo_thread compiled and ran fine on both ubuntu 16.04 and xenomai patched ubuntu 14.04 (without mode switches)

## requirements

branch vberenz/xenomai of mpi_cmake_modules should be merged first.

https://github.com/machines-in-motion/mpi_cmake_modules/pull/9

## issues

Code should not be merged as such !

The API of thread has changed from :

```
int create_realtime_thread(void*(*thread_function)(void*),
                               void* args = nullptr);
```

to:

```
int create_realtime_thread(void(*thread_function)(void*),
                               void* args = nullptr);
```
possibly for bad reason. Xenomai thread spawning function requires a void(*)(void*) and no casting I tried worked. I updated all the demos, but ideally we should find a suitable way to do the casting.

### CODE REVIEW

**Review by MaximilienNaveau — CHANGES_REQUESTED** [review]
I don't think this is how we should do this.

1: The sleep functions are embedded as static methods of the Timer class, because the c++ type of the time object will vary for every sleep function. So we hide this issue in the timer. We could also extract them in a sleep.hpp if needed.
2: For the thread we have specific macros for dealing with the issue you have. See the head of the file thread.hpp: THREAD_FUNCTION_RETURN_TYPE and THREAD_FUNCTION_RETURN_VALUE. These could be renamed but it would break the API.

If you disagree with these point we can talk about it tomorrow.

**Comment by vincentberenz** [comment]
@MaximilienNaveau 

1. I missed the sleep function in Timer. Should indeed use it.

2. I do not understand. We want the same thread_function to work with both xenomai and non xenomai OS, thus the thread creating function should take the same signature in both cases. Or am I missing something ? 

Here the minimal code version of what I am trying to solve:
https://onlinegdb.com/B1e3-3318

**Comment by vincentberenz** [comment]
@MaximilienNaveau 

oh, now I got it : it would require user code to use  THREAD_FUNCTION_RETURN_TYPE and THREAD_FUNCTION_RETURN_VALUE in their code ? Does not look great ...

**Comment by vincentberenz** [comment]
@MaximilienNaveau 

1. I removed sleep.hpp and moved the microseconds sleep to timer.hpp
2. different signatures for create_realtime_thread for xenomai, rtpreempt and non-realtime, using the macros in the demos

**Review by MaximilienNaveau — APPROVED** [review]

**Comment by MaximilienNaveau** [comment]
You can rebase and merge whenever ready with mpi_cmake_modules

**Pull request merged**
