### PR TITLE
fix the spinner behavior in case the iteration takes too long

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
Fix the behavior of the spinner in case the loop iteration takes too long and build 2 unit-tests for the spinner

### CODE REVIEW

**Review by vincentberenz — COMMENTED** [review]
why not:
next_date_sec_ = current_time + period_sec_ ?

**Comment by MaximilienNaveau** [comment]
[edit] Fair point, I just wanted to keep the time proportional to the initial time. I agree what I do maybe useless and add more complexity for nothing. What do you think?

But this way you ensure there are as less drift as possible.

**Comment by wumanu** [comment]
> why not:
> next_date_sec_ = current_time + period_sec_ ?



> [edit] Fair point, I just wanted to keep the time proportional to the initial time. I agree what I do maybe useless and add more complexity for nothing. What do you think?
> 
> But this way you ensure there are as less drift as possible.

I would also have implemented it the way vincent suggested. In fact intuitively this is how I would expect the spinner to behave. of course this will introduce some drift, but I cannot think of any case where this would be a problem.

**Comment by MaximilienNaveau** [comment]
I update the code accordingly.

**Pull request merged**
