### PR TITLE
Bump version to 3.0.0 and add changelog

### PR DESCRIPTION
**Pull request by luator**
## Description
Bump version to 3.0.0 and add a changelog (following the format suggested by https://keepachangelog.com/en/1.0.0/).

In preparation for the upcoming Real Robot Challenge 2022, I'm making versioned releases of our packages and use the occasion to add proper changelog files.

@jviereck @MaximilienNaveau:  It would be great if you could give a brief summary of what was changed in #31 (just "Changes in `UsbStream`" is not very useful^^).

### CODE REVIEW

**Comment by MaximilienNaveau** [comment]
> @jviereck @MaximilienNaveau: It would be great if you could give a brief summary of what was changed in #31 (just "Changes in `UsbStream`" is not very useful^^).

I believe the message should be:

"Add safety checks during the reading of serial port (usb) messages"

**Comment by MaximilienNaveau** [comment]
The CI blocks?

**Comment by MaximilienNaveau** [comment]
The compilation of the documentation is a huge mess... I am sorry for this I don't have the time to maintain it properly
I believe the documentation is using packages that are not maintained properly and hence fails miserably in the build farm...

**Comment by luator** [comment]
> I believe the message should be:
> 
> "Add safety checks during the reading of serial port (usb) messages"

Thanks, I updated the changelog.

I ran into some issue with mistune as well some time ago.  [Fixing the version to <2.0.0](https://github.com/open-dynamic-robot-initiative/trifinger_singularity/blob/6530ddfd1a774d167c177305ca27291e76fb987f/trifinger_base.def#L51) solved it for me.

I also would like to work more on the documentation build (ideally to get rid of the redundant cmake implementation) but likewise didn't have enough time for it yet :/.

**Comment by MaximilienNaveau** [comment]
I think I fixed the CI, I found the same link you sent me aha

**Comment by luator** [comment]
Is it okay if I merge?

**Comment by MaximilienNaveau** [comment]
Go ahead

**Pull request merged**
