### PR TITLE
Update test_threadsafe_timeseries_history

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
update the test to make sure that the data among the threads are rebuilt after each tests

### CODE REVIEW

**Comment by MaximilienNaveau** [comment]
Can I have a very quick pass on this?
and potentially the approval to push this directly to the master to test it on the continuous integration?

**Comment by MaximilienNaveau** [comment]
Ok I take the intiative to try to fix this unittest I won't go through the pull request I will ask you to review the code once it works

**Review by wumanu — COMMENTED** [review]
as far as i can see the second test (partial_history) does not make any sense anymore after your changes. the purpose of this test was to see if the timeseries works if more elements are written to it than it has elements (i.e. it will lose history). as far as i can see after your changes a timeseries of equal length to the data is created, which defeats the purpose of this test.

**Comment by MaximilienNaveau** [comment]
Thanks Manuel for pointing that out. I miss read your code. I guess all I really had to do is increase the sleeping time the slow thread...

Problem solved. I will open an issue in the shared_memory now ^^

**Comment by jviereck** [comment]
> Can I have a very quick pass on this?

What is a "quick pass" - you mean a quick code review or quick approval?

**Comment by wumanu** [comment]
> Thanks Manuel for pointing that out. I miss read your code. I guess all I really had to do is increase the sleeping time the slow thread...
> 
> Problem solved. I will open an issue in the shared_memory now ^^

Yes I think increasing the sleeping time should do the job, even though i am a bit surprised this is necessary. thanks max :)

**Comment by MaximilienNaveau** [comment]
My guess is that the docker is not a real time os therefore if you ask it to sleep a too short time it will not sleep at all. I had to significantly increase the sleeping time (1ms)

**Pull request merged**
