### PR TITLE
vector include bug resolved

### PR DESCRIPTION
**Pull request by amsabyaneh**
catkin_make fails due to this missing include.

### CODE REVIEW

**Review by MaximilienNaveau — APPROVED** [review]

**Comment by MaximilienNaveau** [comment]
Why did the continuous integration not see this?

**Review by luator — APPROVED** [review]

**Comment by luator** [comment]
Ah, thanks for the PR! (I had this fixed locally already but forgot to make a PR...)

@MaximilienNaveau I think due to the OS-depending ifdefs, this only fails when building on a real-time computer (I also only had this on the robot PC, not on my laptop).

**Review by vincentberenz — APPROVED** [review]

**Comment by luator** [comment]
@amsabyaneh Since everyone approved, you can merge this PR

**Comment by amsabyaneh** [comment]
Done.

**Pull request merged**
